// <auto-generated />
namespace WatchWord.Web.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WatchWordWebUIv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WatchWordWebUIv1));
        
        string IMigrationMetadata.Id
        {
            get { return "201512072226143_WatchWord.Web.UI-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
